forge "https://forgeapi.puppetlabs.com"

#mod "puppetlabs/stdlib","4.4.0"
mod "puppetlabs/stdlib","4.8.0"
#mod "puppetlabs/concat","0.2.0"
#mod "puppetlabs/concat","1.2.4"
mod "puppetlabs/motd","1.2.0"
mod "neillturner/role","0.1.3"
mod "saz/vim","2.4.0"
